### ISSUE TITLE
[Feature Request] Option for "start button" or logo icon instead of the word Applications

### ISSUE THREAD

**Issue by DaisyLee2010** [leb-kuchen/cosmic-applet-apps-menu#7]
Is it possible to use an icon for the launcher instead of the word Applications? 

This would make using the applet in a single panel layout much more visually appealing.

**Comment by YkdWaWEzVmphR1Z1** [comment]
Do you have a good icon in mind?

**Comment by DaisyLee2010** [comment]
On one hand I think it should be agnostic and be the COSMICDE logo. But I don't think there is one yet.

Could always use the current Gnome Cosmic App launcher logo from popOS 22.04.


![pop-cosmic-applications](https://github.com/leb-kuchen/cosmic-applet-apps-menu/assets/4692608/b14d989b-ff77-4d7c-81e7-fa402f7036ff)

**Comment by YkdWaWEzVmphR1Z1** [comment]
Fixed in #8 
I did not choose a grid icon, since I do not want it do look similar to the app libary.
